import type { DecisionOption } from "../../types";

export const decisions: Record<string, DecisionOption[]> = {
  "shadow-court": [
    {
      id: "court-investigate",
      text: "公开核查边镇与朝中矛盾",
      description: "让多方拿出证据，暂缓简单定罪。",
      type: "counterfactual",
      allowedRoleIds: ["emperor"],
      stateEffects: { centralAuthority: 4, factionTrust: 8, historicalDrift: 8 },
      nextNodeId: "frontier-break",
      historicalExplanation: "正史中朝廷猜疑和派系冲突不断加深，未能有效拆解边镇兵权问题。",
      resultScript: [{ id: "court-investigate-r", type: "decisionResult", speakerName: "旁白", text: "你要求证据先行，朝中短暂安静下来。可边镇兵权仍在，真正的难题只是被推迟到更清楚的地方。" }],
    },
    {
      id: "court-pressure",
      text: "支持强硬问罪",
      description: "把危机解释为个人叛逆，迅速压迫边镇表态。",
      type: "historical",
      allowedRoleIds: ["emperor"],
      stateEffects: { centralAuthority: -4, factionTrust: -8, historicalDrift: -2 },
      nextNodeId: "frontier-break",
      historicalExplanation: "朝廷对边镇的疑惧与安禄山的野心互相刺激，局势很快滑向叛乱。",
      resultScript: [{ id: "court-pressure-r", type: "decisionResult", speakerName: "旁白", text: "强硬命令让朝臣看见了态度，也让边镇更容易把起兵包装成自保。局势没有被压住，反而更紧。" }],
    },
    {
      id: "consort-distance",
      text: "劝亲族降低锋芒",
      description: "你不能改朝政，但能尝试减少怨气指向。",
      type: "counterfactual",
      allowedRoleIds: ["consort"],
      stateEffects: { publicResentment: -6, factionTrust: 4, historicalDrift: 6 },
      nextNodeId: "frontier-break",
      randomEventId: "message-breaks-through",
      historicalExplanation: "宫廷人物难以直接改变制度失衡，但能影响局部观感与信息传递。",
      resultScript: [{ id: "consort-distance-r", type: "decisionResult", speakerName: "旁白", text: "你的劝说没有让风暴停下，却让少数人开始意识到：怨气若只找一个出口，真相会被遮住。" }],
    },
    {
      id: "commander-report",
      text: "把真实军情写得更直",
      description: "冒着被认为怯战的风险，把前线风险说清楚。",
      type: "counterfactual",
      allowedRoleIds: ["commander"],
      stateEffects: { factionTrust: 6, militaryMorale: 2, historicalDrift: 5 },
      nextNodeId: "frontier-break",
      randomEventId: "message-breaks-through",
      historicalExplanation: "前线真实信息若能更早进入决策，可能降低误判，但未必能改变朝中派系压力。",
      resultScript: [{ id: "commander-report-r", type: "decisionResult", speakerName: "旁白", text: "你把话写得很重。信送出去后，你知道这未必能改变上面的想法，但至少不是沉默地等命令落下。" }],
    },
    {
      id: "guard-listen",
      text: "记录军中怨言并上报",
      description: "把基层的不满变成可以被看见的消息。",
      type: "counterfactual",
      allowedRoleIds: ["guard"],
      stateEffects: { publicResentment: -3, factionTrust: 3, historicalDrift: 4 },
      nextNodeId: "frontier-break",
      randomEventId: "message-breaks-through",
      historicalExplanation: "基层不能扭转大势，但能改变怨气是否在沉默中积累。",
      resultScript: [{ id: "guard-listen-r", type: "decisionResult", speakerName: "旁白", text: "你把听见的话交上去。它也许会被压住，但至少有人第一次把军士当成局势的一部分，而不是只会服从的影子。" }],
    },
  ],
  "frontier-break": [
    {
      id: "frontier-defend-capital",
      text: "稳住长安，优先整合防线",
      description: "承认叛军强势，先把各路防线和粮道接起来。",
      type: "counterfactual",
      allowedRoleIds: ["emperor"],
      stateEffects: { centralAuthority: 4, militaryMorale: 5, historicalDrift: 8 },
      nextNodeId: "tong-pass",
      historicalExplanation: "更稳健的防线整合可能减轻恐慌，但朝廷仍要面对边镇兵权过重的结构性难题。",
      resultScript: [{ id: "frontier-defend-r", type: "decisionResult", speakerName: "旁白", text: "你没有把胜负押在一句强硬话上，而是先补防线。朝中有人嫌慢，但前线终于得到一点喘息。" }],
    },
    {
      id: "consort-seek-protection",
      text: "寻找愿意作证的人",
      description: "让身边人说明危机并非一人一族造成。",
      type: "counterfactual",
      allowedRoleIds: ["consort"],
      stateEffects: { factionTrust: 4, publicResentment: -4, historicalDrift: 6 },
      nextNodeId: "tong-pass",
      resultScript: [{ id: "consort-protection-r", type: "decisionResult", speakerName: "旁白", text: "你开始寻找愿意说实话的人。保护不一定来得及，但证词会决定后来的人怎样理解你。" }],
      historicalExplanation: "被卷入权力中心的人常难以改变大势，但可以影响责任如何被分配。",
    },
    {
      id: "commander-hold",
      text: "坚持固守，不主动出关",
      description: "用地形拖住叛军，拒绝被情绪带进野战。",
      type: "counterfactual",
      allowedRoleIds: ["commander"],
      stateEffects: { militaryMorale: 7, factionTrust: -4, historicalDrift: 10 },
      nextNodeId: "tong-pass",
      historicalExplanation: "固守潼关是更符合地形优势的判断，但朝廷压力会把它解释为迟疑。",
      resultScript: [{ id: "commander-hold-r", type: "decisionResult", speakerName: "旁白", text: "你把军令压在守字上。士兵心里稍稳，朝中的疑心却更重了。" }],
    },
    {
      id: "guard-follow",
      text: "继续服从，但要求补给说法",
      description: "不煽动同袍，却把最基本的问题摆出来。",
      type: "counterfactual",
      allowedRoleIds: ["guard"],
      stateEffects: { militaryMorale: 3, publicResentment: -3, historicalDrift: 4 },
      nextNodeId: "tong-pass",
      resultScript: [{ id: "guard-follow-r", type: "decisionResult", speakerName: "旁白", text: "你没有把怨气喊成哗变，但也没有继续装作没事。队伍暂时还走得动，怨气被看见了一点。" }],
      historicalExplanation: "普通军士不能决定战略，但能影响军中怨气是否提前爆开。",
    },
  ],
  "tong-pass": [
    {
      id: "pass-order-attack",
      text: "命令出关决战",
      description: "用一场胜利来证明朝廷仍有威严。",
      type: "historical",
      allowedRoleIds: ["emperor"],
      stateEffects: { centralAuthority: -10, militaryMorale: -14, historicalDrift: -3 },
      nextNodeId: "mawei-crisis",
      historicalExplanation: "正史中潼关防线崩溃后，长安迅速暴露，皇帝西逃。",
      resultScript: [{ id: "pass-attack-r", type: "decisionResult", speakerName: "旁白", text: "命令落下，关门打开。你要的是威严，可战场只认地形、士气和时机。" }],
    },
    {
      id: "pass-allow-hold",
      text: "允许继续固守",
      description: "承受朝中压力，把主动权留给防线。",
      type: "counterfactual",
      allowedRoleIds: ["emperor", "commander"],
      stateEffects: { militaryMorale: 10, factionTrust: 2, historicalDrift: 14 },
      nextNodeId: "mawei-crisis",
      randomEventId: "troop-accepts-compromise",
      historicalExplanation: "固守可能拖慢叛军，但不能自动解决朝廷财政、派系和边镇制度问题。",
      resultScript: [{ id: "pass-hold-r", type: "decisionResult", speakerName: "旁白", text: "关隘暂时没有被交出去。所有人都松了一口气，但你知道，这只是把更大的问题拖进下一天。" }],
    },
    {
      id: "consort-send-warning",
      text: "托人提醒不要把失败归咎于宫中",
      description: "尝试切断怨气转向替罪羊的路径。",
      type: "counterfactual",
      allowedRoleIds: ["consort"],
      stateEffects: { publicResentment: -5, factionTrust: 3, historicalDrift: 6 },
      nextNodeId: "mawei-crisis",
      randomEventId: "message-breaks-through",
      historicalExplanation: "这不能改变军事胜负，却可能改变逃亡路上的责任叙事。",
      resultScript: [{ id: "consort-warning-r", type: "decisionResult", speakerName: "旁白", text: "你把话递出去：战败不是一个名字能解释的。可当人群需要发泄时，理清责任本身也成了危险的事。" }],
    },
    {
      id: "guard-prepare-retreat",
      text: "和同袍约定撤退秩序",
      description: "不讨论大人物的输赢，先减少路上的失控。",
      type: "counterfactual",
      allowedRoleIds: ["guard"],
      stateEffects: { militaryMorale: 5, publicResentment: -2, historicalDrift: 5 },
      nextNodeId: "mawei-crisis",
      resultScript: [{ id: "guard-retreat-r", type: "decisionResult", speakerName: "旁白", text: "你们约好谁扶伤兵、谁看粮车、谁压住最激动的人。大势仍坏，但队伍没有立刻碎掉。" }],
      historicalExplanation: "基层安排无法逆转战局，却能影响逃亡中的生死和军心。",
    },
  ],
  "mawei-crisis": [
    {
      id: "mawei-sacrifice",
      text: "接受军中追责要求",
      description: "用牺牲换取护驾队伍继续前进。",
      type: "historical",
      allowedRoleIds: ["emperor", "general", "guard"],
      stateEffects: { centralAuthority: -12, militaryMorale: 8, publicResentment: -10, historicalDrift: -2 },
      nextNodeId: "new-center",
      historicalExplanation: "马嵬坡事变中，禁军要求诛杀杨国忠，杨贵妃也被迫身死，队伍继续西行。",
      resultScript: [{ id: "mawei-sacrifice-r", type: "decisionResult", speakerName: "旁白", text: "队伍终于动了。可这不是胜利，只是用一个无法收回的代价换来继续逃亡的秩序。" }],
    },
    {
      id: "mawei-protect",
      text: "公开分责，拒绝简单牺牲",
      description: "承认朝政失误，同时要求军队接受约束。",
      type: "counterfactual",
      allowedRoleIds: ["emperor", "consort", "general", "guard"],
      stateEffects: { centralAuthority: 4, factionTrust: 8, publicResentment: 4, historicalDrift: 16 },
      nextNodeId: "new-center",
      randomEventId: "troop-accepts-compromise",
      historicalExplanation: "这种选择可能保住个体命运，但军心是否接受并不确定，逃亡队伍仍可能崩裂。",
      resultScript: [{ id: "mawei-protect-r", type: "decisionResult", speakerName: "旁白", text: "你把责任摊开来说，试图阻止所有怒火压到一个人身上。人群沉默了片刻，接下来要看他们是否还愿意相信命令。" }],
    },
    {
      id: "commander-testimony",
      text: "留下前线证词",
      description: "说明战局崩坏并非单一人物造成。",
      type: "counterfactual",
      allowedRoleIds: ["commander"],
      stateEffects: { factionTrust: 5, historicalDrift: 7 },
      nextNodeId: "new-center",
      randomEventId: "message-breaks-through",
      historicalExplanation: "证词不能改变已经发生的失败，却能影响责任如何被记录。",
      resultScript: [{ id: "commander-testimony-r", type: "decisionResult", speakerName: "旁白", text: "你写下关隘、军令和真实士气。历史不一定会听你辩解，但沉默会让最方便的说法变成唯一的说法。" }],
    },
  ],
  "new-center": [
    {
      id: "ending-historical",
      text: "承认大势已改，保存余下秩序",
      description: "让新的权力中心组织平叛，自己退到历史后景。",
      type: "historical",
      allowedRoleIds: ["emperor", "consort", "commander", "guard"],
      stateEffects: { centralAuthority: -4, militaryMorale: 4 },
      historicalExplanation: "安史之乱最终被平定，但唐朝中央权威受损，地方军权问题延续。",
      resultScript: [{ id: "ending-historical-r", type: "decisionResult", speakerName: "旁白", text: "战乱会结束，伤口不会立刻合上。你看见一个时代转身，也看见每个人只能带着自己的代价走出去。" }],
    },
    {
      id: "ending-reform",
      text: "推动战后追责与军权约束",
      description: "不把平叛当成终点，尝试处理制度裂缝。",
      type: "counterfactual",
      allowedRoleIds: ["emperor", "commander", "guard"],
      stateEffects: { centralAuthority: 8, factionTrust: 6, historicalDrift: 12 },
      historicalExplanation: "战后若更早约束地方军权，可能改善局部，但财政、藩镇和朝廷互信仍是长期难题。",
      resultScript: [{ id: "ending-reform-r", type: "decisionResult", speakerName: "旁白", text: "你不再把叛乱只当成坏人的故事。制度裂缝被摆上桌面，能不能补上，仍要看更多人愿不愿意付代价。" }],
    },
    {
      id: "ending-survival",
      text: "保住局部命运和证词",
      description: "接受大历史难改，优先改变身边人的生死和后来叙述。",
      type: "counterfactual",
      allowedRoleIds: ["consort", "guard", "commander"],
      stateEffects: { factionTrust: 4, historicalDrift: 10 },
      historicalExplanation: "不是每个角色都能改变大历史，但可以改变局部命运、关系和历史解释。",
      resultScript: [{ id: "ending-survival-r", type: "decisionResult", speakerName: "旁白", text: "你没有改写整个时代，却让几个名字不再只是被推着走。对身在风暴里的人来说，这已经不是小事。" }],
    },
  ],
};
