import type { NPCProfile } from "../../types";
import { assets } from "./assets";

export const npcs: NPCProfile[] = [
  {
    id: "rebel",
    name: "安禄山",
    identity: "边镇节度使，掌握强大兵力，表面称臣，实际已有更大野心。",
    globalStance: "利用朝廷疑惧与边镇兵权扩大自己的主动权。",
    personality: "外表粗豪亲近，话里常带试探和推诿。",
    knowledgeBoundary: "知道自己辖区兵力、朝廷对他的疑心和起兵准备；不知道朝廷内部每个临时决定。",
    portraitImage: assets.portraits.rebel,
    promptProfileKey: "frontier-warlord",
  },
  {
    id: "minister",
    name: "杨国忠",
    identity: "权相，掌握朝政话语权，树敌很多。",
    globalStance: "急于证明自己判断正确，也急于把危险推向前线解决。",
    personality: "锋利、焦躁、善于把责任转给别人。",
    knowledgeBoundary: "知道朝中派系压力和对安禄山的指控；不了解前线所有细节。",
    portraitImage: assets.portraits.minister,
    promptProfileKey: "court-minister",
  },
  {
    id: "commander",
    name: "哥舒翰",
    identity: "守关将领，掌握前线真实军情。",
    globalStance: "主张利用险要地形固守，反对仓促出击。",
    personality: "直白、疲惫、重视实际兵力。",
    knowledgeBoundary: "知道关隘、防线和士气；不知道宫廷逃亡后的细节。",
    portraitImage: assets.portraits.commander,
    promptProfileKey: "frontline-commander",
  },
  {
    id: "general",
    name: "陈玄礼",
    identity: "禁军将领，能约束随驾军士，也必须面对军中怒火。",
    globalStance: "要保护皇帝，但不能无视军心崩裂。",
    personality: "克制、沉重、话不多但有压迫感。",
    knowledgeBoundary: "知道禁军情绪和护驾路线；不知道朝廷所有秘密安排。",
    portraitImage: assets.portraits.general,
    promptProfileKey: "guard-general",
  },
  {
    id: "attendant",
    name: "高力士",
    identity: "皇帝身边近臣，熟悉宫廷情绪和皇帝软肋。",
    globalStance: "尽量保全皇帝与宫廷核心，但会提醒现实代价。",
    personality: "谨慎、委婉、懂得留余地。",
    knowledgeBoundary: "知道皇帝身边人的态度和宫廷消息；不掌握前线全部战报。",
    portraitImage: assets.portraits.attendant,
    promptProfileKey: "inner-court",
  },
  {
    id: "scout",
    name: "斥候",
    identity: "传递前线与道路消息的小吏或军士。",
    globalStance: "只关心消息是否能送到，以及自己能否活着回来。",
    personality: "紧张、直接、看见什么说什么。",
    knowledgeBoundary: "知道自己刚看到的路况、军情和流言；不知道高层真实谋划。",
    portraitImage: assets.portraits.scout,
    promptProfileKey: "field-scout",
  },
];
